version: 2
jobs:
  frontend:
    working_directory: ~/Nomoriam/client
    docker:
      - image: circleci/node:10
    steps:
      - checkout:
          path: ~/Nomoriam
      - run:
          name: install npm
          command: npm install
      - run:
          name: install npm
          command:  |
            cd client && \
            ls
      - run:
          name: build react
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --project $PROJECT_ID --token "$TOKEN_FIREBASE"
workflows:
  version: 2
  deploy:
    jobs:
          - frontend:
              filters:
                branches:
                  only:
                    - master