export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const CREATE_CHALLENGE = 'CREATE_CHALLENGE'
export const FETCH_CHALLENGES_APPROVE = 'FETCH_CHALLENGES_APPROVE'
export const FETCH_CHALLENGES_NOTFOUND = 'FETCH_CHALLENGES_NOTFOUND'
export const APPROVE_CHALLENGES = 'APPROVE_CHALLENGES'




export const FETCH_CHALLENGES = 'FETCH_CHALLENGES'
export const FETCH_CHALLENGE = 'FETCH_CHALLENGE'
export const ADD_ACTIVITY = 'ADD_ACTIVITY'
export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES'
export const JOIN_CHALLENGE = 'JOIN_CHALLENGE'
export const FETCH_CHALLENGE_BY_PLAYER = 'FETCH_CHALLENGE_BY_PLAYER'
export const DO_POST = 'DO_POST'
export const FETCH_POST = 'FETCH_POST'
