/*
    Auth Action
*/

export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED'
export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED'
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const INITIAL_PROFILE = 'INITIAL_PROFILE'
export const INITIAL_PROFILE_CLEAN = 'INITIAL_PROFILE_CLEAN'
export const EDITE_PHOTO = 'EDITE_PHOTO'
export const EDITE_PROFILE = 'EDITE_PROFILE'
export const EDITE_CLEAN = 'EDITE_CLEAN'


/*
    Challenge Action
*/

export const CREATE_CHALLENGE = 'CREATE_CHALLENGE'
export const CREATE_CHALLENGE_FAILED = 'CREATE_CHALLENGE_FAILED'
export const FETCH_CHALLENGE_ON_APPROVE = 'FETCH_CHALLENGE_ON_APPROVE'
export const FETCH_CHALLENGE_BY_INDEX = 'FETCH_CHALLENGE_BY_INDEX'
export const FETCH_CHALLENGE_BY_INDEX_CLEAN_UP = "FETCH_CHALLENGE_BY_INDEX_CLEAN_UP"
export const FETCH_MY_CHALLENGE = 'FETCH_MY_CHALLENGE'
export const FETCH_MY_CHALLENGES = 'FETCH_MY_CHALLENGES'
export const FETCH_MY_CHALLENGES_CLEAN = 'FETCH_MY_CHALLENGES_CLEAN'
export const FETCH_POST = 'FETCH_POST'

/* 
    Challenge Action Blockchain
*/
export const CLEAN_UP = 'CLEAN_UP'

export const APPROVE_CHALLENGES = 'APPROVE_CHALLENGES'
export const FETCH_CHALLENGES = 'FETCH_CHALLENGES'
export const FETCH_CHALLENGE = 'FETCH_CHALLENGE'
export const FETCH_CHALLENGE_CLEAN_UP = 'FETCH_CHALLENGE_CLEAN_UP'
export const JOIN_CHALLENGE = 'JOIN_CHALLENGE'
export const JOIN_CHALLENGE_CLEAN_UP = 'JOIN_CHALLENGE_CLEAN_UP'
export const FETCH_ACTIVITY = 'FETCH_ACTIVITY'
export const DOPOST = 'DOPOST'
export const DOPOST_CLEAN = 'DOPOST_CLEAN'
export const DOQRCODE = 'DOQRCODE'
export const DOQRCODE_CLEAN = 'DOQRCODE_CLEAN'
export const FETCH_JOINED = 'FETCH_JOINED'
export const CLEAR_JOINED = 'CLEAR_JOINED'
export const FETCH_PLAYERS = 'FETCH_PLAYERS'
export const CLEAR_PLAYERS = 'CLEAR_PLAYERS'
